In [86]:
import tensorflow as tf
import pandas as pd
import numpy as np

import os
os.getcwd();

In [87]:
#---------------------------------------------------
# 데이터을 로딩
df= pd.read_csv("thoracic_surgery.csv")
df.head()

icd10   fvc  fev1 zubrod   pain  haemoptysis  dyspnoea  cough  weakness  \
0  DGN2  2.88  2.16   PRZ1  False        False     False   True      True   
1  DGN3  3.40  1.88   PRZ0  False        False     False  False     False   
2  DGN3  2.76  2.08   PRZ1  False        False     False   True     False   
3  DGN3  3.68  3.04   PRZ0  False        False     False  False     False   
4  DGN3  2.44  0.96   PRZ2  False         True     False   True      True   

  tumor_size  diabetes  mi_6months  peri_artery_disease  smoking  asthma  age  \
0       OC14     False       False                False     True   False   60   
1       OC12     False       False                False     True   False   51   
2       OC11     False       False                False     True   False   59   
3       OC11     False       False                False    False   False   54   
4       OC11     False       False                False     True   False   73   

   died  
0     0  
1     0  
2     0  
3     0  
4     1

In [88]:
# Converting Object dat types variables to integer data type
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 470 entries, 0 to 469
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   icd10                470 non-null    object 
 1   fvc                  470 non-null    float64
 2   fev1                 470 non-null    float64
 3   zubrod               470 non-null    object 
 4   pain                 470 non-null    bool   
 5   haemoptysis          470 non-null    bool   
 6   dyspnoea             470 non-null    bool   
 7   cough                470 non-null    bool   
 8   weakness             470 non-null    bool   
 9   tumor_size           470 non-null    object 
 10  diabetes             470 non-null    bool   
 11  mi_6months           470 non-null    bool   
 12  peri_artery_disease  470 non-null    bool   
 13  smoking              470 non-null    bool   
 14  asthma               470 non-null    bool   
 15  age                  470 non-null    int

In [89]:
df.head()

icd10   fvc  fev1 zubrod   pain  haemoptysis  dyspnoea  cough  weakness  \
0  DGN2  2.88  2.16   PRZ1  False        False     False   True      True   
1  DGN3  3.40  1.88   PRZ0  False        False     False  False     False   
2  DGN3  2.76  2.08   PRZ1  False        False     False   True     False   
3  DGN3  3.68  3.04   PRZ0  False        False     False  False     False   
4  DGN3  2.44  0.96   PRZ2  False         True     False   True      True   

  tumor_size  diabetes  mi_6months  peri_artery_disease  smoking  asthma  age  \
0       OC14     False       False                False     True   False   60   
1       OC12     False       False                False     True   False   51   
2       OC11     False       False                False     True   False   59   
3       OC11     False       False                False    False   False   54   
4       OC11     False       False                False     True   False   73   

   died  
0     0  
1     0  
2     0  
3     0  
4     1

In [90]:
#---------------------------------------------------
# Boolean 데이터를 Integer로 변경
df[['pain', 
    'haemoptysis', 
    'dyspnoea', 
    'cough', 
    'weakness',  
    'diabetes',
    'mi_6months',
    'peri_artery_disease',
    'smoking',
    'asthma']] = np.where(
    df[['pain',
    'haemoptysis', 
    'dyspnoea', 
    'cough', 
    'weakness',  
    'diabetes',
    'mi_6months',
    'peri_artery_disease',
    'smoking',
    'asthma']].astype(str) == 'True', 1, 0)
df.head()

icd10   fvc  fev1 zubrod  pain  haemoptysis  dyspnoea  cough  weakness  \
0  DGN2  2.88  2.16   PRZ1     0            0         0      1         1   
1  DGN3  3.40  1.88   PRZ0     0            0         0      0         0   
2  DGN3  2.76  2.08   PRZ1     0            0         0      1         0   
3  DGN3  3.68  3.04   PRZ0     0            0         0      0         0   
4  DGN3  2.44  0.96   PRZ2     0            1         0      1         1   

  tumor_size  diabetes  mi_6months  peri_artery_disease  smoking  asthma  age  \
0       OC14         0           0                    0        1       0   60   
1       OC12         0           0                    0        1       0   51   
2       OC11         0           0                    0        1       0   59   
3       OC11         0           0                    0        0       0   54   
4       OC11         0           0                    0        1       0   73   

   died  
0     0  
1     0  
2     0  
3     0  
4     1

In [91]:
#---------------------------------------------------
# String 데이터를 Integer로 변경
df['icd10'] = df['icd10'].str[-1:].astype(int)
df['zubrod'] = df['zubrod'].str[-1:].astype(int)
df['tumor_size'] = df['tumor_size'].str[-1:].astype(int)
df.head()

icd10   fvc  fev1  zubrod  pain  haemoptysis  dyspnoea  cough  weakness  \
0      2  2.88  2.16       1     0            0         0      1         1   
1      3  3.40  1.88       0     0            0         0      0         0   
2      3  2.76  2.08       1     0            0         0      1         0   
3      3  3.68  3.04       0     0            0         0      0         0   
4      3  2.44  0.96       2     0            1         0      1         1   

   tumor_size  diabetes  mi_6months  peri_artery_disease  smoking  asthma  \
0           4         0           0                    0        1       0   
1           2         0           0                    0        1       0   
2           1         0           0                    0        1       0   
3           1         0           0                    0        0       0   
4           1         0           0                    0        1       0   

   age  died  
0   60     0  
1   51     0  
2   59     0  
3   54     0  
4   73     1

In [92]:
data_set = df.values # 실제 데이터만 array 형태로 읽어온다
data_set

array([[ 2.  ,  2.88,  2.16, ...,  0.  , 60.  ,  0.  ],
       [ 3.  ,  3.4 ,  1.88, ...,  0.  , 51.  ,  0.  ],
       [ 3.  ,  2.76,  2.08, ...,  0.  , 59.  ,  0.  ],
       ...,
       [ 3.  ,  3.04,  2.08, ...,  0.  , 52.  ,  0.  ],
       [ 3.  ,  1.96,  1.68, ...,  0.  , 79.  ,  0.  ],
       [ 3.  ,  4.72,  3.56, ...,  0.  , 51.  ,  0.  ]])

In [93]:
#---------------------------------------------------
# 데이터를 학습데이터, 테스트데이터로 분리
from sklearn.model_selection import train_test_split

train, test = train_test_split(data_set, test_size = 0.2) # 20%를 테스트 데이터로 사용
test.shape

(94, 17)

In [94]:
train.shape

(376, 17)

In [95]:
#속성과 라벨(클래스) 분리하기
x_train = train[:, 0:16] # 0,1,2,3,...,15,16
y_train = train[:, 16]
x_train

array([[ 3.  ,  2.56, 60.9 , ...,  1.  ,  0.  , 50.  ],
       [ 3.  ,  2.8 ,  2.32, ...,  1.  ,  0.  , 57.  ],
       [ 3.  ,  3.36,  2.8 , ...,  1.  ,  0.  , 76.  ],
       ...,
       [ 3.  ,  2.44,  0.96, ...,  1.  ,  0.  , 73.  ],
       [ 3.  ,  2.32,  1.96, ...,  1.  ,  0.  , 61.  ],
       [ 3.  ,  2.22,  1.36, ...,  1.  ,  0.  , 63.  ]])

In [96]:
#속성과 라벨(클래스) 분리하기
x_test = test[:, 0:16] # 0,1,2,3,...,15,16
y_test = test[:, 16]
y_test

array([0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 0., 0., 1., 0., 0., 0., 0.])

In [97]:
from keras.models import Sequential
from keras.layers import Dense

# Sequential 객체, model 생성
model = Sequential()

# 2개의 층을 추가
model.add(Dense(30, input_dim = 16, activation='relu')) # activation 0, 1 판별함수, 1이면 다음 노드로 넘김
model.add(Dense(1, activation='sigmoid'))

model.compile(
    loss='mean_squared_error', 
    optimizer='adam', 
    metrics=['accuracy'])# 역추적하는 함수로 adam을 사용

In [98]:
model.fit(
    x_train, y_train, 
    epochs=30, 
    batch_size=10)

Epoch 1/30
376/376 [==============================] - 0s 333us/step - loss: 0.1345 - accuracy: 0.8484
Epoch 2/30
376/376 [==============================] - 0s 114us/step - loss: 0.1316 - accuracy: 0.8537
Epoch 3/30
376/376 [==============================] - 0s 122us/step - loss: 0.1299 - accuracy: 0.8537
Epoch 4/30
376/376 [==============================] - 0s 125us/step - loss: 0.1292 - accuracy: 0.8537
Epoch 5/30
376/376 [==============================] - 0s 117us/step - loss: 0.1275 - accuracy: 0.8537
Epoch 6/30
376/376 [==============================] - 0s 122us/step - loss: 0.1287 - accuracy: 0.8537
Epoch 7/30
376/376 [==============================] - 0s 136us/step - loss: 0.1322 - accuracy: 0.8537
Epoch 8/30
376/376 [==============================] - 0s 122us/step - loss: 0.1275 - accuracy: 0.8537
Epoch 9/30
376/376 [==============================] - 0s 138us/step - loss: 0.1264 - accuracy: 0.8537
Epoch 10/30
376/376 [==============================] - 0s 128us/step - loss: 0.125

In [102]:
score = model.evaluate(x_test, y_test)
print('loss=', score[0])
print('accuracy=', score[1])

94/94 [==============================] - 0s 53us/step
loss= 0.13722291176623486
accuracy= 0.8404255509376526


In [103]:
prediction = model.predict_classes(x_test)
prediction.ravel()

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0])

In [104]:
# 예측결과 출력
import pandas as pd

comparison = pd.DataFrame({'prediction':prediction.ravel(), 'ground_truth':y_test}).astype('int')
pd.set_option('display.max_rows', None)
comparison
# 정확도 너무 떨어지는데..?

prediction  ground_truth
0            0             0
1            0             0
2            0             0
3            0             1
4            0             0
5            0             1
6            0             0
7            0             0
8            0             0
9            0             0
10           0             0
11           0             0
12           0             0
13           0             0
14           0             1
15           0             0
16           0             0
17           0             0
18           0             1
19           0             0
20           0             0
21           0             0
22           0             0
23           0             0
24           0             0
25           0             0
26           0             0
27           0             0
28           0             0
29           0             1
30           0             0
31           0             0
32           0             0
33           0             0
34           0             0
35           0             0
36           0             1
37           0             0
38           0             0
39           0             0
40           0             0
41           0             0
42           0             0
43           0             0
44           0             0
45           0             1
46           0             0
47           0             0
48           0             0
49           0             0
50           0             0
51           0             0
52           0             1
53           0             0
54           0             0
55           0             1
56           0             0
57           0             0
58           0             0
59           0             0
60           0             1
61           0             0
62           0             1
63           0             0
64           0             0
65           0             0
66           0             0
67           0             0
68           0             0
69           0             0
70           0             0
71           0             0
72           0             1
73           0             0
74           0             0
75           0             0
76           0             0
77           0             1
78           0             0
79           0             0
80           0             0
81           0             0
82           0             0
83           0             0
84           0             0
85           0             1
86           0             0
87           0             0
88           0             0
89           0             1
90           0             0
91           0             0
92           0             0
93           0             0